### ISSUE TITLE
Trying to work with MOSES Dataset

### ISSUE THREAD

**Issue by leosv123** [DeepGraphLearning/torchdrug#10]
dataset.num_bond_type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/torchdrug/torchdrug/data/dataset.py", line 168, in num_bond_type
    return len(self.bond_types)
  File "torchdrug/torchdrug/utils/decorator.py", line 21, in __get__
    result = self.func(obj)
  File "torchdrug/torchdrug/data/dataset.py", line 183, in bond_types
    bond_types.update(graph.edge_list[:, 2].tolist())
AttributeError: 'NoneType' object has no attribute 'edge_list'

**Comment by leosv123** [comment]
but It's working fine with the ZInc dataset

**Comment by Oxer11** [comment]
Hi! This seems a bug in torchdrug. 

The MOSES (ZINC2m) dataset is loaded in a lazy mode by default. This means that we only load the first element into self.data and all other elements will be loaded when the corresponding __getitem__ method is called. But when calling the bond_types method, we need all elements in the dataset, including those unloaded ones. So this leads to the Error in this issue.

Thanks for your issue. We will fix this as soon as possible.

**Comment by Oxer11** [comment]
Fixed in 6151fa9
