### ISSUE TITLE
A problem with Retrosynthesis

### ISSUE THREAD

**Issue by lemon-prog123** [DeepGraphLearning/torchdrug#102]
Hi, I have build a pipline with your guideline in Retrosynthesis Moudle. It works well on default dataset. But when I tried to test it on my own smiles, there was something wrong with it. To be specific, I convert my smiles with `data.Molecule.from_smiles(smile,node_feature="synthon_completion", kekulize=True)`  just as test_set do. But it seems that the molecule in test set has 43 types of nodes. But my converted molecule from smiles only has 39 types of nodes. So it can't be sent to the model as the input-dims is 43.

How can I fix it?

For example,my smile "C=C(CC)C(C)(C)C"

**Comment by zqsaudience** [comment]
Hi，Can I find out how you solved this problem?
