### ISSUE TITLE
Un-standardization of predict method in PropertyPrediction

### ISSUE THREAD

**Issue by kanojikajino** [DeepGraphLearning/torchdrug#109]
As far as I understand, `PropertyPrediction` task trains a predictor against the standardized target values (for example, the loss is computed against the standardized target values at this [line](https://github.com/DeepGraphLearning/torchdrug/blob/b0bd1c6428a74d0cd49c6015f201a7eef545390f/torchdrug/tasks/property_prediction.py#L86)), and therefore, 
 the method [`predict`](https://github.com/DeepGraphLearning/torchdrug/blob/b0bd1c6428a74d0cd49c6015f201a7eef545390f/torchdrug/tasks/property_prediction.py#L103) in `PropertyPrediction` is designed to output the standardized prediction, whose mean equals 0 and std equals 1. I felt this is a bit confusing for users, because the output of `predict` has to be calibrated by users after calling `predict`, which could be forgotten and then could lead to suboptimal predictive performance.

To this end, I would like to ask,
1. whether my understanding on `predict` is correct,
2. the reason why the output of `predict` has to be standardized, and
3. if there is no solid reason on it, whether I can fix it so that the output of `predict` is non-standardized, which will include destructive changes on APIs.

**Comment by Oxer11** [comment]
Hi! Thanks for your advise!

Yes, your understanding on `predict` is correct. The output of `predict` was originally designed for the `forward` function, where we define the loss function. However, we think that following your suggestions to make the output of `predict` non-strandardized would be more friendly to users.

Feel free to open a pull request for this issue! We will include this change in next release version.

**Comment by kanojikajino** [comment]
Hi, I created a pull request #111, fixing the issue. I would appreciate it if you could review it and merge it if appropriate.
