### ISSUE TITLE
Inconsistent outputs of "functional.generalized_rspmm" on cpu and gpu

### ISSUE THREAD

**Issue by yzhangee** [DeepGraphLearning/torchdrug#110]
Hello, I want to use this function for GNN-based KG. But the results are not as expected. To figure out the problem, I write a simple case for testing. It seems that the results on `cpu` and `cuda` are quite different.

```
import numpy as np
import torch
from torchdrug.layers import functional

edges = np.array([[0,0,0],[0,1,0],[1,0,0]])
values = np.array([1,1,1])
adj = torch.sparse_coo_tensor(indices=torch.LongTensor(edges).t(), values=torch.FloatTensor(values), size=(2,2,1)).cuda()


head = torch.FloatTensor([[1],[1]]).cuda()
rela = torch.FloatTensor([[1]]).cuda()

tail = functional.generalized_rspmm(adj, rela, head,sum='add',mul='mul')
print(tail)
```

Without ".cuda()", the print result is tensor([[2.], [1.]]).
With ".cuda()", the print result is tensor([[0.], [0.]], device='cuda:0').

The environment is GeForce RTX 3090 GPU with CUDA Version: 11.2. Python 3.9.7, PyTorch 1.10.2+cu111. Torch-scatter runs smoothly on this environment. But torchdrug has some problem. 

Do you have any suggestions to solve this problem? Thanks!

**Comment by KiddoZhu** [comment]
Hi! I just gave a quick reproduction on a similar setting: RTX 3060, Python 3.7.9, PyTorch 1.8.1+cu111. Both CPU and CUDA output the correct result, and I am a little bit confused.

The CUDA kernel for rspmm should be right -- at least it passed our tests before. The output zeros might come from the initial value for `sum` aggregation, and I guess it might be `-inf` if you change to `max` aggregation. If that's the case, it means you access the output tensor before the asynchronous computation is done. Maybe PyTorch has some updates on tensor synchronization and we need to modify our rspmm implementation correspondingly.

You may try `torch.cuda.synchornize(device)` before printing the output variable. If that still happens, I guess you have to roll back to PyTorch 1.8 before we fix that.

**Comment by yzhangee** [comment]
Thanks for your quick response! I solved this problem by reinstalling the cuda library. The other things are unchanged. Maybe there is some inconsistency in the library I used before.
