### ISSUE TITLE
Pipeline to get graph encoding from a list of smiles

### ISSUE THREAD

**Issue by ethancohen123** [DeepGraphLearning/torchdrug#122]
Hi,
I would like to know (if it is possible) how to get the graph from a list of smiles and then feed it into a GNN ( GIN for example) to get their embedding ? 
Thanks

**Comment by KiddoZhu** [comment]
Yes. You may use `data.PackedMolecule.from_smiles` to create a batch of graph from a list of smiles. Check the documentation [here](https://torchdrug.ai/docs/api/data.html#torchdrug.data.PackedMolecule.from_smiles).
