### ISSUE TITLE
ValueError: Fail to parse the docstring of `Smol`. Inconsistent number of parameters in signature and docstring.

### ISSUE THREAD

**Issue by CaiYitao** [DeepGraphLearning/torchdrug#124]
Trying to build a customized dataset as follows for the molecular generation task. 

```python
@R.register("datasets.Smol")

@doc.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))

class Smol(data.MoleculeDataset):

  smiles_file = "/content/drive/MyDrive/molecule_design/resources/smiles_train.csv"
  target_fields = ["SPLIT"]

  def __init__(self, smiles_file, verbose=1, **kwargs):
    self.load_csv(self.smiles_file, smiles_field="smiles", target_fields=self.target_fields,lazy=True,
                      verbose=verbose, **kwargs)
    
  def split(self):
    indexes = defaultdict(list)
    for i, split in enumerate(self.targets["SPLIT"]):
        indexes[split].append(i)
    train_set = torch_data.Subset(self, indexes["train"])
    valid_set = torch_data.Subset(self, indexes["valid"])
    test_set = torch_data.Subset(self, indexes["test"])
    return train_set, valid_set, test_set
```

but get the following error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-29-ada51874abcc>](https://localhost:8080/#) in <module>()
      3 @doc.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
      4 
----> 5 class Smol(data.MoleculeDataset):
      6 
      7   smiles_file = "/content/drive/MyDrive/molecule_design/resources/smiles_train.csv"

[/usr/local/lib/python3.7/dist-packages/torchdrug/utils/doc.py](https://localhost:8080/#) in wrapper(obj)
     90         if len(docs) != len(parameters):
     91             raise ValueError("Fail to parse the docstring of `%s`. "
---> 92                              "Inconsistent number of parameters in signature and docstring." % obj.__name__)
     93         new_params = []
     94         new_docs = []

ValueError: Fail to parse the docstring of `Smol`. Inconsistent number of parameters in signature and docstring.
```
Did I miss something?

**Comment by KiddoZhu** [comment]
Hi! The decorator `@doc.copy_args` is only used for auto-filling the `**kwargs` part in the docstring. If your class doesn't have a valid docstring, please just remove the decorator.

**Comment by CaiYitao** [comment]
Just tried it, works now! Thanks for your kind reply!

**Comment by CaiYitao** [comment]
> Trying to build a customized dataset as follows for the molecular generation task.
> 
> ```python
> @R.register("datasets.Smol")
> 
> @doc.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
> 
> class Smol(data.MoleculeDataset):
> 
>   smiles_file = "/content/drive/MyDrive/molecule_design/resources/smiles_train.csv"
>   target_fields = ["SPLIT"]
> 
>   def __init__(self, smiles_file, verbose=1, **kwargs):
>     self.load_csv(self.smiles_file, smiles_field="smiles", target_fields=self.target_fields,lazy=True,
>                       verbose=verbose, **kwargs)
>     
>   def split(self):
>     indexes = defaultdict(list)
>     for i, split in enumerate(self.targets["SPLIT"]):
>         indexes[split].append(i)
>     train_set = torch_data.Subset(self, indexes["train"])
>     valid_set = torch_data.Subset(self, indexes["valid"])
>     test_set = torch_data.Subset(self, indexes["test"])
>     return train_set, valid_set, test_set
> ```
> 
> but get the following error:
> 
> ```python
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> [<ipython-input-29-ada51874abcc>](https://localhost:8080/#) in <module>()
>       3 @doc.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
>       4 
> ----> 5 class Smol(data.MoleculeDataset):
>       6 
>       7   smiles_file = "/content/drive/MyDrive/molecule_design/resources/smiles_train.csv"
> 
> [/usr/local/lib/python3.7/dist-packages/torchdrug/utils/doc.py](https://localhost:8080/#) in wrapper(obj)
>      90         if len(docs) != len(parameters):
>      91             raise ValueError("Fail to parse the docstring of `%s`. "
> ---> 92                              "Inconsistent number of parameters in signature and docstring." % obj.__name__)
>      93         new_params = []
>      94         new_docs = []
> 
> ValueError: Fail to parse the docstring of `Smol`. Inconsistent number of parameters in signature and docstring.
> ```
> 
> Did I miss something?

now there is another problem coming out:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-c7e661af9d82> in <module>
      1 optimizer = optim.Adam(task.parameters(), lr = 1e-3)
      2 solver = core.Engine(task, train_set, valid_set, test_set, optimizer,
----> 3                      gpus=(0,), batch_size=128, log_interval=10)
<decorator-gen-126> in __init__(self, task, train_set, valid_set, test_set, optimizer, scheduler, gpus, batch_size, gradient_interval, num_worker, logger, log_interval)

2 frames
/usr/local/lib/python3.7/dist-packages/torchdrug/core/core.py in wrapper(init, self, *args, **kwargs)
    286                 config.pop(k)
    287             self._config = dict(config)
--> 288             return init(self, *args, **kwargs)
    289 
    290         def get_function(method):

/usr/local/lib/python3.7/dist-packages/torchdrug/core/engine.py in __init__(self, task, train_set, valid_set, test_set, optimizer, scheduler, gpus, batch_size, gradient_interval, num_worker, logger, log_interval)
     90             # handle dynamic parameters in optimizer
     91             old_params = list(task.parameters())
---> 92             result = task.preprocess(train_set, valid_set, test_set)
     93             if result is not None:
     94                 train_set, valid_set, test_set = result

/usr/local/lib/python3.7/dist-packages/torchdrug/tasks/generation.py in preprocess(self, train_set, valid_set, test_set)
    667         Compute ``max_edge_unroll`` and ``max_node`` on the training set if not provided.
    668         """
--> 669         remap_atom_type = transforms.RemapAtomType(train_set.atom_types)
    670         train_set.transform = transforms.Compose([
    671             train_set.transform,

AttributeError: 'Subset' object has no attribute 'atom_types'
```

**Comment by KiddoZhu** [comment]
For generative models, since there is no need to use validation and test sets. You may pass the full dataset as the training set, and set None for both validation and test sets. See the [demo of GCPN / GraphAF](https://colab.research.google.com/drive/1JEMiMvSBuqCuzzREYpviNZZRVOYsgivA?usp=sharing#forceEdit=true&sandboxMode=true&scrollTo=Jh7S-aX_gJ1w).

GraphAF might take a long time to train, since it is an autoregressive model, though I can't recall the exact speed of GraphAF. For the CUDA support problem, it is because you install the CPU version rather than the GPU version of torch_scatter.
