### ISSUE TITLE
module 'torchdrug.datasets' has no attribute 'BetaLactamase'

### ISSUE THREAD

**Issue by JiYuanFeng** [DeepGraphLearning/torchdrug#127]
Hi, thanks for the nice codebase. I try to follow the tutorial from the https://torchprotein.ai/. However, current torchdrug package seems not provide related datasets. How can I deal with this?  Thanks again for your kind reply

**Comment by JiYuanFeng** [comment]
Hello, any update？ Looking forward to your enthusiastic response

**Comment by KiddoZhu** [comment]
Hi! Thanks for your interest in TorchProtein. TorchProtein is still under development and the website is just a draft. It may take some time before we get a release version of TorchProtein.

**Comment by JiYuanFeng** [comment]
Hi! Thanks for the information. Looking forward!
