### ISSUE TITLE
Loading EnzymeCommission/enzyme_commission.pkl.gz failed

### ISSUE THREAD

**Issue by ShoufaChen** [DeepGraphLearning/torchdrug#135]
Hello,

Thanks for this awesome open-source work.

I met an issue with the multi-processing loading data https://github.com/DeepGraphLearning/GearNet/issues/2.

When using multiple GPUs, each process would load an independent `enzyme_commission.pkl.gz` to the memory. It is OK on my machine when the number of processing less than 4.

**Comment by Oxer11** [comment]
Hi Shoufa!

Thanks for raising this issue! I think this is a memory issue and I've replied in https://github.com/DeepGraphLearning/GearNet/issues/2.
