### ISSUE TITLE
ModuleNotFoundError: No module named 'esm.model.esm1'; 'esm.model' is not a package

### ISSUE THREAD

**Issue by hxu105** [DeepGraphLearning/torchdrug#145]
ModuleNotFoundError: No module named 'esm.model.esm1'; 'esm.model' is not a package

**Comment by KiddoZhu** [comment]
Hi! I guess this is due to new versions of the esm package. Could you try to downgrade esm to 0.3.0?

**Comment by hxu105** [comment]
Thanks, this solves my problem

**Comment by JasonHuangChina** [comment]
> Hi! I guess this is due to new versions of the esm package. Could you try to downgrade esm to 0.3.0?

It still doesn't work

**Comment by key262yek** [comment]
On the version 2.0.0, it still happens
