### ISSUE TITLE
PackedProtein representation

### ISSUE THREAD

**Issue by hxu105** [DeepGraphLearning/torchdrug#151]
Hi, I am trying to figure out the input data structure, and here is the sequence representation from a packedprotein structure. Could you help to explain about the .G in the sequence? Many thanks!
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/40327643/200136577-63d4dfe5-4601-45bc-8e6a-28f9e259c139.png">

**Comment by KiddoZhu** [comment]
`G` means glycine. `.` is a separator for multiple sequences. This means that your second protein contains a lot of isolated glycines.
