### ISSUE TITLE
ValueError: Unknown value `CHI_SQUAREPLANAR`.

### ISSUE THREAD

**Issue by anar-rzayev** [DeepGraphLearning/torchdrug#153]
When I am running tutorial 4 (https://torchprotein.ai/tutorial_4) for making a class toy for Enzyme Commission, I get the value error of Unknown value `CHI_SQUAREPLANAR`. Available vocabulary is `range(0, 4)` Could anyone suggest how to fix this issue? Thanks!

**Comment by Oxer11** [comment]
Hi! Sorry for the inconvenience!

The reason has been explained in [this issue](https://github.com/DeepGraphLearning/GearNet/issues/5). And I have changed the tutorial accordingly. It should be right if you follow the current tutorial.

**Comment by anar-rzayev** [comment]
Oh, that is fast and nice. Thank you for such a convenient solution!
