### ISSUE TITLE
[Bug Report] SubsequenceNode IndexError 

### ISSUE THREAD

**Issue by Mrz-zz** [DeepGraphLearning/torchdrug#158]
Hey, I found one bug when using the `SubsequenceNode` because of the inconsistency of the residue_mask and node_mask. 

The residue number and node number is not the same without using `layers.GraphConstruction` to transform the original protein view into the residue-level graph.

**Comment by Oxer11** [comment]
Thanks for pointing out the bug! This has been fixed in 4e76c30.

**Comment by Mrz-zz** [comment]
Thank you for your work !
