### ISSUE TITLE
`num_relation` mismatches in `message_and_aggregate()`

### ISSUE THREAD

**Issue by goga0001** [DeepGraphLearning/torchdrug#159]
I would like to use my custom data https://raw.githubusercontent.com/goga0001/graph/main/data.csv
 I prepared the data as CSV file and followed the implementation of existing datasets:

```python
import os
from torchdrug import data, utils
from torchdrug.core import Registry as R
from collections import defaultdict
from torch.utils import data as torch_data
from torchdrug import data
from torchdrug.utils import doc


@R.register("datasets.Flavonoid2")
@doc.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
class Flavonoid2(data.MoleculeDataset):
    """
    Subset of Flavonoid compound database for virtual screening.

    Statistics:
        - #Molecule:  4806
        - #Regression task: 2

    Parameters:
        path (str): path to store the dataset
        verbose (int, optional): output verbose level
        **kwargs
    """

    csv_file = "/content/torchdrug/torchdrug/datasets/data.csv"
    target_fields = ["logP","qed"]

    def __init__(self, path, verbose=1, **kwargs):
        self.load_csv(self.csv_file, smiles_field="smiles", target_fields=self.target_fields,
                      verbose=verbose, **kwargs)
```
**Molecules were constructed from smiles but I get assertion error:**
```python
from torch import nn, optim
optimizer = optim.Adam(task.parameters(), lr = 1e-3)
solver = core.Engine(task, dataset, None, None, optimizer,
                     gpus=(0,), batch_size=128, log_interval=10)

solver.train(num_epoch=1)
solver.save("graphaf_flavonoid_1epoch.pkl")
```

```bash
AssertionError                            Traceback (most recent call last)
[<ipython-input-23-a6a027c50b11>](https://localhost:8080/#) in <module>
      4                      gpus=(0,), batch_size=128, log_interval=10)
      5 
----> 6 solver.train(num_epoch=1)
      7 solver.save("graphaf_flavonoid_1epoch.pkl")

10 frames
[/content/torchdrug/torchdrug/layers/conv.py](https://localhost:8080/#) in message_and_aggregate(self, graph, input)
    414 
    415     def message_and_aggregate(self, graph, input):
--> 416         assert graph.num_relation == self.num_relation
    417 
    418         node_in, node_out, relation = graph.edge_list.t()

AssertionError:
```
Thank you! Looking forward to your reply!

**Comment by KiddoZhu** [comment]
Hi! Your code for custom dataset is right.

The problem is that you have different number of relations for your dataset and your model. This is typically caused by the `kekulize` option of the dataset. One safe way is to define the number of relations for your model based on `dataset.num_bond_type`. For GraphAF, I would recommend to use `kekulize=True`.

**Comment by goga0001** [comment]
Hello, thank you for your quick reply!
I actually used `kekulize=True` in this line of code but it still gives the same Assertion Error:

`dataset = Flavonoid3("/content/torchdrug/torchdrug/datasets/data.csv", kekulize=True,
                            atom_feature="symbol")`

**Comment by KiddoZhu** [comment]
Could you check `dataset.num_bond_type`, `model.model.layers[0].num_relation` (for GraphAF model) and `dataset[0].num_relation`?

**Comment by goga0001** [comment]
`dataset.num_bond_type`
`2`

`model.layers[0].num_relation`
`2`

`dataset[0].num_relation`
`AttributeError: 'dict' object has no attribute 'num_relation'`

`dataset[0] `
`{'graph': Molecule(num_atom=22, num_bond=50),
 'logP': -0.8174,
 'qed': 0.565067144}`

**Comment by goga0001** [comment]
Maybe I can give a minimal repro example that you can run?

**Comment by KiddoZhu** [comment]
> Maybe I can give a minimal repro example that you can run?

Yes please. What about `dataset[0]["graph"].num_relation`?

**Comment by goga0001** [comment]
Here is the link to minimal repro:
https://github.com/goga0001/graph/blob/main/minimal%20repro.ipynb

`dataset[0]["graph"].num_relation`
`3`

Thanks again!
