### ISSUE TITLE
can't process data on GPU -- dict of size 1?

### ISSUE THREAD

**Issue by parsifal9** [DeepGraphLearning/torchdrug#171]
HI All,
I want to load a larger data set and fit a trained model to it. 
The dataset is loaded into "datasetRNN" without a problem. However I am finding that it won't fit on a GPU. 

I have tried subsetting it without any success. "batch" seems to be a dict of length 1, so I can't get the keys and subset it that way.
What sort of object is "batch" and how can I process it in chunks?

Bye

```
batch = data.graph_collate(datasetRNN )
batch = utils.cuda(batch)
pred = task.predict(batch)
#RuntimeError: CUDA out of memory. Tried to allocate 2.92 GiB (GPU 0; 15.90 GiB total capacity; 14.81 GiB already allocated; 319.81 MiB free; 14.85 GiB reserved in total by PyTorch)

len(batch)
# 1
batch.keys()
#dict_keys(['graph'])
batch.items()
# dict_items([('graph', PackedMolecule(batch_size=454081, num_atoms=[24, 28, 34, ..., 21, 21, 25],
# num_bonds=[50, 60, 76, ..., 46, 46, 54], device='cuda:0'))])

```

**Comment by Oxer11** [comment]
Hi, the [`graph_collate`](https://torchdrug.ai/docs/api/data.html?highlight=graph_collate#torchdrug.data.graph_collate) function will merge differenet samples in a batch by concatenating values for each key. To access the size of each batch, you can take a look at `len(batch['graph'])`. In your case, the batch_size is 454081, which means you're trying to collate the whole dataset. This will cause out of CUDA memory. You can try a smaller batch size.

**Comment by parsifal9** [comment]
thanks for that Oxer11, however I am still confused by something
1) by batch size, do you mean the batch_size from the solver? i.e.
```
solver = core.Engine(task, train_set, valid_set, test_set, optimizer, gpus=[0], batch_size=1024)
```
2) that is set to 1024 and also I am not fitting to this data set. I trained on this data set and am now making predictions on 
a new, larger data set
3) the only thing that has circumvented the limit on the GPU is this 
```
set1, set2  = torch.utils.data.random_split(datasetRNN,
                                         lengths=[ 1000, 453081],
                                           generator=torch.Generator().manual_seed(42))
batch = data.graph_collate(set1)
len(batch['graph']) #1167
batch = utils.cuda(batch)
pred1 = task.predict(batch)
```
but now I have predictions on a random subsets of my data -- not much good.

**Comment by Oxer11** [comment]
Hi!

If you want to use a new dataset for testing, you can just pass it into the solver as `test_set`. The solver will use your specified `batch_size` when making predictions on your test set (plz refer to [this](https://torchdrug.ai/docs/_modules/torchdrug/core/engine.html#Engine.evaluate)). That's how we use solver to save time for writing training and testing procedure.

If you still want to write the test procedure by yourself, you need to write a loop and define a sampler. Each time you will sample a batch to pass into your model instead of directly passing the whole dataset. This is essentially what we do in [`solver.evaluate`](https://torchdrug.ai/docs/_modules/torchdrug/core/engine.html#Engine.evaluate).

**Comment by parsifal9** [comment]
Hi Oxer11
do you mean like this, where datasetRNN is the new data that I want a prediction on?
```
solver = core.Engine(task, train_set, valid_set, datasetRNN, optimizer, gpus=[0], batch_size=100)
solver.evaluate("test")
#KeyError: 'Activity'
```
It gives an error as there is no  'Activity' variable in the datasetRNN data set. This is what I want to predict.

I took up your other comments and wrote a dataloader i.e 
```
outputs = []
loader  = data.DataLoader(dataset, batch_size=1024)
for batch in loader:
    batch = utils.cuda(batch)
    outputs.append(task.predict(batch))
outputs = torch.cat(outputs, dim=0)
```
which works perfectly for "dataset" -- which I trained on.
However for the datasetRNN data set, even with  batch_size=1, it gives a memory error. i,e
```
outputs = []
loader  = data.DataLoader(datasetRNN, batch_size=1)
for batch in loader:
     batch = utils.cuda(batch)
     outputs.append(task.predict(batch))
.
.
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 15.90 GiB total capacity; 14.91 GiB already allocated; 5.81 MiB free; 15.15 GiB reserved in total by PyTorch)
```
This seems very odd. I must be missing something
Bye

**Comment by Oxer11** [comment]
This is weird. In your previous reply, the model can run with batch_size 1000 but fails with batch_size 1 in your latest implememntation. Could you show your implementation of `datasetRNN`?

**Comment by parsifal9** [comment]
Hi Oxer11,
thank you for all your help with this.

yes I think it is weird also and well beyond me. I have included all the code below, in blocks.
block 3 is the one you asked for. 

1) I load the MIT data set (2335 samples) and train a model on it
2) I make a dataloader and get predictions on the MIT data set -- all this woks with no problem
3) I load the large data set,  datasetRNN  (454,700 samples)
4) I make a dataloader and try to get predictions on this data set
and that is where the problem appears. It fails for batch_size=1 and for batch_size=1024

block 1
```
import os
import torch
from torchdrug import data, utils
from torchdrug.core import Registry as R

@R.register("datasets.Ecoli")
@utils.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
class Ecoli(data.MoleculeDataset):
    """
    E. coli test of drug activity

    Statistics:
        - #Molecule: 2,335
        - #Classification task: 2

    Parameters:
        path (str): path to store the dataset
        verbose (int, optional): output verbose level
        **kwargs
    """
    
    url = "/scratch1/dun280/torch_drug/X1.csv"
    target_fields = ["Activity"]

    def __init__(self, path, verbose=1, **kwargs):
        path = os.path.expanduser(path)
        if not os.path.exists(path):
            os.makedirs(path)
        self.path = path
        csv_file = self.url
        self.load_csv(csv_file, smiles_field="SMILES", target_fields=self.target_fields,
                      verbose=verbose, **kwargs)
dataset = Ecoli("./X1.csv")
# Ecoli(
  #sample: 2335
  #task: 1
# )

# test/ train validate data sets 
from torchdrug import data, datasets
lengths = [int(0.8 * len(dataset)), int(0.1 * len(dataset))]
lengths += [len(dataset) - sum(lengths)]
#[1868, 233, 234]
train_set, valid_set, test_set = torch.utils.data.random_split(dataset, lengths,generator=torch.Generator().manual_seed(42))

# The model 
from torchdrug import core, models, tasks, utils
model = models.GIN(input_dim=dataset.node_feature_dim,
                   hidden_dims=[256, 256, 256, 256],
                   short_cut=True, batch_norm=True, concat_hidden=True)
task = tasks.PropertyPrediction(model, task=dataset.tasks,
                                criterion="bce", metric=("auprc", "auroc"))

# Train and Test
optimizer = torch.optim.Adam(task.parameters(), lr=1e-3)
solver = core.Engine(task, train_set, valid_set, test_set, optimizer, gpus=[0], batch_size=1024)
#solver = core.Engine(task, train_set, valid_set, test_set, optimizer, batch_size=1024)
solver.train(num_epoch=100)
 
#Once the model is trained, we evaluate it on the validation set. The result may be similar to the following.
solver.evaluate("valid")
```


block 2  --  I make a dataloader and get predictions on the MIT data set -- all this works with no problem
```
# predict "activity" for a data set
# create a DataLoader and put the data through. This works  for the MIT data
outputs = []
loader  = data.DataLoader(dataset, batch_size=1024)

for batch in loader:
    batch = utils.cuda(batch)
    outputs.append(task.predict(batch))

outputs = torch.cat(outputs, dim=0)
```
block 3 -- I load the large data set datasetRNN  (454,700 samples)
```
import os
from torchdrug import data, utils
from torchdrug.core import Registry as R

@R.register("datasets.publicxRNN")
@utils.copy_args(data.MoleculeDataset.load_csv, ignore=("smiles_field", "target_fields"))
class publicxRNN(data.MoleculeDataset):
    """
    LSTM-generated_molecules.smiles Public RNN generated compounds from DOI 10.1021-acscentsci.7b00512.zip

    Statistics:
        - #Molecule: 454,700

    Parameters:
        path (str): path to store the dataset
        verbose (int, optional): output verbose level
        **kwargs
    """   
    url = "/datasets/work/d61-ai4dd-datashare-point/reference/LSTM-generated_molecules.smiles"

    target_fields = []
    def __init__(self, path, verbose=1, **kwargs):
        path = os.path.expanduser(path)
        if not os.path.exists(path):
            os.makedirs(path)
        self.path = path
        csv_file = self.url
        self.load_csv(csv_file, smiles_field="SMILES", target_fields=self.target_fields,
                      verbose=verbose, **kwargs)

datasetRNN = publicxRNN("/datasets/work/d61-ai4dd-datashare-point/reference/LSTM-generated_molecules.smiles")
```

block 4  - I make a dataloader and try to get predictions on this data set and that is where the problem appears.
```
outputs = []
loader  = data.DataLoader(datasetRNN, batch_size=100)

for batch in loader:
    batch = utils.cuda(batch)
    outputs.append(task.predict(batch))

#batch_size=1024)
#RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 15.90 GiB total capacity; 14.83 GiB already allocated#; 13.81 MiB free; 15.14 GiB reserved in total by PyTorch)

#batch_size=100)
#RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 14.38 GiB already allocated#; 5.81 MiB free; 15.15 GiB reserved in total by PyTorch)

```

**Comment by Oxer11** [comment]
Everything looks good to me. Maybe you need to check the size of molecules in your dataset to avoid OOM.

**Comment by mgolebiewski** [comment]
Hi @parsifal9 ,

Regarding the code in block 4, despite batch_size=100, the whole file will be loaded at once and converted to molecules. In order to load only batch_size chunks of data in each loop iteration, you also need lazy=True when instantiating your Dataloader:
`loader  = data.DataLoader(datasetRNN, batch_size=100, lazy=True)`

The other issue is with this line:
`outputs.append(task.predict(batch))`
task.predict(batch) creates a new tensor on the GPU. When it's appended to the outputs list, it effectively prevents the garbage collector from freeing the GPU memory taken by this tensor. Since you are trying to process a large dataset with hundreds of thousands of samples, you will run out of memory (and I think this is actually the core cause of the issues you were facing).

What you really want to do is to append just the values of the tensor elements to your outputs, so that the tensor (or its memory) can be recycled:
`outputs = outputs + list(np.concatenate(task.predict(batch).tolist()))`
Looks a bit cryptic, but it's because .tolist() returns a list with individual values nested as single element lists, so we need to flatten it. You'll need to import numpy for this to work, too.

Final version of the code in block 4 with both suggestions implemented:
```
import numpy as np

outputs = []
loader  = data.DataLoader(datasetRNN, batch_size=100, lazy=True)

for batch in loader:
    batch = utils.cuda(batch)
    outputs = outputs + list(np.concatenate(task.predict(batch).tolist()))
```

Note that this code works also with lazy=False (which is default), the only difference is with lazy=False it spends long time loading the whole file before the loop, with lazy=True each individual batch is loaded when executing this line:
`for batch in loader:`

**Comment by parsifal9** [comment]
Hi @mgolebiewski ,

thanks for your help and your clear explanation. 
That worked and the data set was processed with no other problems. 
I will close this issue now.
Bye
