### ISSUE TITLE
How to create a data.Protein instance from scratch

### ISSUE THREAD

**Issue by dongli96** [DeepGraphLearning/torchdrug#174]
I now have 100 protein residues and 3-D coordinates of those (simply speaking, just 100 points, no PDB file, Mol file, etc.). I am wondering how to build a data.Protein instance with those residues as nodes and residue "coordinates" as `node_position`, then use `layers.KNNEdge`, etc. to add edges to it.

On a machine with Ubuntu 20.4, Python 3.9, Pytorch 13.1+117cu, I tried:
```
X = ...  # tensor [100, 3]
prot = data.Protein(num_node=100, node_position=X, view="residue")
```
It reported "ValueError: `atom_type` should be provided". This confuses me as I treat residues as nodes here.

**Comment by Oxer11** [comment]
Hi!

To define a protein or molecule, you need to specify the atom_type, bond_type and residue_type. Otherwise, I would suggest you to treat the protein as a vanilla graph defined by `data.Graph(num_node=100, node_position=X)`.

**Comment by dongli96** [comment]
Thank you for your suggestion. Unfortunately it seems impossible to add edges to a `data.Graph` instance using edge layers like `KNNEdge`. Is there any solution to this problem?

**Comment by Oxer11** [comment]
Hi! I guess the error is due to the lack of `atom2residue` infromation. You can either provide the information in the protein or simply set `min_distance=0` and `max_distance=0`.
