### ISSUE TITLE
functional.generalized_rspmm

### ISSUE THREAD

**Issue by Xnhyacinth** [DeepGraphLearning/torchdrug#188]
why functional.generalized_rspmm keep running with no result and no error，it's just stuck there. so are simple examples：

```python
import numpy as np
import torch
from torchdrug.layers import functional

edges = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0]])
values = np.array([1, 1, 1])
adj = torch.sparse_coo_tensor(indices=torch.LongTensor(edges).t(), values=torch.FloatTensor(values),
                              size=(2, 2, 1)).cuda()

head = torch.FloatTensor([[1], [1]]).cuda()
rela = torch.FloatTensor([[1]]).cuda()

tail = functional.generalized_rspmm(adj, rela, head, sum='add', mul='mul')
print(tail)
```

**Comment by KiddoZhu** [comment]
Hi! It is likely due to a broken JIT cache for `generalized_rspmm`. This happens when you try to kill the process during JIT compilation and then rerun the program. Could you try to free the cache by `rm -rf ~/.cache/torch_extensions`?

See more discussions here https://github.com/DeepGraphLearning/torchdrug/issues/8#issuecomment-933169689.

**Comment by Xnhyacinth** [comment]
OK! Thanks, I have successfully solved it, just free the cache by&nbsp;rm -rf ~/.cache/torch_extensions.
Thanks!




&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DeepGraphLearning/torchdrug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 凌晨2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DeepGraphLearning/torchdrug] functional.generalized_rspmm (Issue #188)





 
Hi! It is likely due to a broken JIT cache for generalized_rspmm. This happens when you try to kill the process during JIT compilation and then rerun the program. Could you try to free the cache by rm -rf ~/.cache/torch_extensions?
 
See more discussions here #8 (comment).
