### ISSUE TITLE
Shape mismatch in GeometricRelationalGraphConv

### ISSUE THREAD

**Issue by pearl-rabbit** [DeepGraphLearning/torchdrug#189]
I encountered a shape mismatch issue during runtime.
```
File "/home/admin/anaconda3/envs/test_env/lib/python3.7/site-packages/torchdrug-0.2.0-py3.7.egg/torchdrug/layers/conv.py", line 813, in message_and_aggregate
    return update.view(graph.num_node, self.num_relation * self.input_dim)
RuntimeError: shape '[975, 472]' is invalid for input of size 312000
```
protein structure:
```
print(protein, protein.node_feature.shape)  # PackedProtein(batch_size=1, num_atoms=[51], num_bonds=[975], num_residues=[51])   torch.Size([51, 21])
```
code:
```
gearnet_edge = GearNet(input_dim=21, hidden_dims=[512, 512, 512, 512, 512, 512],
                       num_relation=7, edge_input_dim=59, num_angle_bin=8,
                       batch_norm=True, concat_hidden=True, short_cut=True,
                       readout="sum")
output = gearnet_edge(protein, protein.node_feature.float(), all_loss=None, metric=None)
```

**Comment by Oxer11** [comment]
Hi, to use the GearNet model, you need to define a `graph_construction_model` to reconstruct the edges in the graph instead of using the original ones in dataset processsing. Otherwise, the number of relations will be mismatched. Please refer to [this tutorial](https://torchprotein.ai/tutorial_3).

**Comment by Chris-Tang6** [comment]
I do use the `graph_construction_model` in my code, but still meet this same error😥. #200 

> Hi, to use the GearNet model, you need to define a `graph_construction_model` to reconstruct the edges in the graph instead of using the original ones in dataset processsing. Otherwise, the number of relations will be mismatched. Please refer to [this tutorial](https://torchprotein.ai/tutorial_3).

**Comment by pearl-rabbit** [comment]
Hello @Chris-Tang6 , you can refer to [this](https://github.com/DeepGraphLearning/GearNet/issues/24).I have already solved this problem, so I will close it first.
