### ISSUE TITLE
Mapping atom_feature to actual atom types

### ISSUE THREAD

**Issue by jonasjuerss** [DeepGraphLearning/torchdrug#197]
Hi,

I struggle to find a way to map the `atom_feature` attribute to the actual atom (e.g. carbon). I would be more than thankful if anyone could point me to e.g. where this is defined in the source code. Generally, I think it might be worth considering to mention this somewhere in the documentation as well.

**Comment by Oxer11** [comment]
Hi, you can find how the `atom_feature` is constructed [here](https://torchdrug.ai/docs/_modules/torchdrug/data/feature.html#atom_default). For atom type, the one-hot feature is constructed according to `atom_vocab`, which you can find in the same file.

**Comment by jonasjuerss** [comment]
Thanks, not sure how I oversaw that class. However, one clarification in case anyone has a similar issue: `atom_type` represents the [atomic number](https://www.daylight.com/meetings/summerschool98/course/dave/smiles-atoms.html) and not the number given in `atom_vocab` [here](https://torchdrug.ai/docs/_modules/torchdrug/data/feature.html).
