### ISSUE TITLE
a question about features on edges and nodes.

### ISSUE THREAD

**Issue by chenzhongwu** [DeepGraphLearning/torchdrug#198]
Does torchdrug support multi features on edges (nodes), like dgl.edata (dgl.ndata)? 
If yes, how to implement it?
Thanks.

**Comment by Oxer11** [comment]
Hi, I'm not familiar with the multi-features in dgl. But you can define and register your customized features as in [data.features](https://torchdrug.ai/docs/_modules/torchdrug/data/feature.html#atom_default).

**Comment by chenzhongwu** [comment]
Here's what I want to do: build a graph with several kinds of features (i,e, R1, R2, R3) on all edges, use functions like GNN or graph matching, and do a graph-related task like link prediction. 
I find torchdrug can only build a graph with one feature (i,e, R) on edges and many functions in torchdrug only support operations over triples (head, R, tail). My goal is to use torchdrug with some modifications and reason over links like (head, R1, R2, R3, tail). 
I think, except for data.features, there are many functions needed to be rewritten to meet my goal. Is that right? Do you have some suggestions for me to achieve my goal using torchdrug?
Thanks!

**Comment by chenzhongwu** [comment]
Thanks！
