### ISSUE TITLE
Where are optimizers registered? 

### ISSUE THREAD

**Issue by yunxiaoliCB** [DeepGraphLearning/torchdrug#201]
I was running a train script by providing a config file which specifies configurations of some Configurable classes. When providing a .yaml config file containing the following snippet:
```
optimizer:
  class: Adam
  lr: 1.0e-3
```
torchdrug can construct an optimizer according to it, i.e., `optimizer = core.Configurable.load_config_dict(cfg.optimizer)`. But I can not find where is Adam optimizer registered in torchdrug's codebase. 

A bit of supplementary info: I tried register another class with registered name being `optimizers.Adam`. Then when using the same config, it throws KeyError: 'Ambiguous key `Adam`. Found `optim.Adam`, `optimizers.Adam`'. This indicates that there is a `optim.Adam` registered somewhere in torchdrug, but I couldn't find it by searching for @R.register("optim.Adam"). 

Where is it registered? (And in general, if there are other optimizers/schedulers registered, where are they located?) 
Thank you!

**Comment by Oxer11** [comment]
Hi, for easy loading with yaml files, we register some essential classes in pytorch in the [patch.py](https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/patch.py) file. You can do similar things if you want to register your customized optimizers.
