### ISSUE TITLE
How to modify the dataset when can't construct protein graph from pdb?

### ISSUE THREAD

**Issue by Chris-Tang6** [DeepGraphLearning/torchdrug#203]
Hello, torchdrug team! 
When I using the `load_pdbs ` func, some PDB files cant' be constructed to a graph and will be skipped directly.
For example, there are 200 data in the dataset, but only 190 in the protein.pkl. 

Then use the `get_item` operation in dataset will occur out of idx ERROR.  

The solution I came up with is to delete the item in dataset when faile  to construct graph in `load_pdbs ` func. In this case, I will rewrite the `load_ pdbs` function. Is there a better way?

**Comment by Oxer11** [comment]
Hi, the failure of loading new PDB files may be due to the strict constraints of rdkit. There are two solutions for this problem:
1. Delete the files directly from your dataset (maybe manually).
2. Rewrite the `data.ProteinDataset` with other pdb loading libraries or loading formats, e.g., https://github.com/DeepGraphLearning/GearNet/blob/7873e2e594234ab581a1119c6ce2f09800593e0e/gearnet/dataset.py#L56.

**Comment by Chris-Tang6** [comment]
Thank you very much🤗🤗 
I have rewritten `load_pdbs` function in my customized `ProteinDataset` and it runs well.
```
    def load_pdbs_drop(self, pdb_files, transform=None, verbose=0):
        self.data = []
        self.pdb_files = []
        self.sequences = []
        self.transform = transform

        drop_ids = []
        drop_pdbs = []
        if verbose:
            pdb_files = tqdm(pdb_files, "Constructing proteins from pdbs")
        for i, pdb_file in enumerate(pdb_files):
            mol = Chem.MolFromPDBFile(pdb_file)
            if not mol:
                logger.debug("Can't construct molecule from pdb file `%s`. Drop this sample." % pdb_file)
                drop_ids.append(i)
                drop_pdbs.append(pdb_file)
                continue
            protein = data.Protein.from_molecule(mol)
            if not protein:
                logger.debug("Can't construct protein from pdb file `%s`. Drop this sample." % pdb_file)
                drop_ids.append(i)
                drop_pdbs.append(pdb_file)
                continue

            if hasattr(protein, "residue_feature"):
                with protein.residue():
                    protein.residue_feature = protein.residue_feature.to_sparse()
            self.data.append(protein)
            self.pdb_files.append(pdb_file)
            self.sequences.append(protein.to_sequence() if protein else None)
        # 在drop后，重新设置索引
        print(f'Drop ids {drop_ids}, they are {drop_pdbs}.')
        self.df = self.df.drop(self.df.index[drop_ids])
        self.df.reset_index(drop=True)  
```

**Comment by jinzhuwei** [comment]
> Hello, I want to use this method to build proteinGraph on my own pdb dataset, but I don't like to write this code, there are always a lot of protein data that cannot be read, I want to ask you if you have the complete code to share with me for me to learn, thank you very much for sharing.

**Comment by Chris-Tang6** [comment]
> > Hello, I want to use this method to build proteinGraph on my own pdb dataset, but I don't like to write this code, there are always a lot of protein data that cannot be read, I want to ask you if you have the complete code to share with me for me to learn, thank you very much for sharing.

Ok, my customized Dataset as below. 
The `load_pdbs_drop` function is to construct protein graph, if some pdbs couldn't be construct, then they will be removed from the dataset list, `seld.df`.

[ScopeSuperFamilyClassify.txt](https://github.com/DeepGraphLearning/torchdrug/files/12101465/ScopeSuperFamilyClassify.txt)
