### ISSUE TITLE
CPU usage too hight, up to 3000%

### ISSUE THREAD

**Issue by Chris-Tang6** [DeepGraphLearning/torchdrug#209]
Hi, torchdrug team!
When I use the the torchdrug to construct my model I find that the cpu usage are too high(3800+%) in training stage. I find it mainly occurs at the dataset. 
I customize my own dataset by following the [torchdrug.dataset.alphafolddbd](https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/datasets/alphafolddb.py). The **_clone()_** and **_to_dense()_** cost many resources. 
Is a problem with the dataset? Are there any solutions to solve it. 
Thank you very much!

![image](https://github.com/DeepGraphLearning/torchdrug/assets/53926670/537d6c2d-f469-4968-8072-23ed7e09e2d5)

![image](https://github.com/DeepGraphLearning/torchdrug/assets/53926670/ae5665d5-c589-4d45-9404-b51124db529a)

**Comment by KiddoZhu** [comment]
Hi! TorchDrug mostly uses PyTorch operations to process datasets on CPUs. By default, PyTorch will utilize multiple CPU threads whenever possible. You can disable the parallelism of PyTorch by calling `torch.set_num_threads(1)`, at the cost of slower CPU operations.

**Comment by Chris-Tang6** [comment]
> Hi! TorchDrug mostly uses PyTorch operations to process datasets on CPUs. By default, PyTorch will utilize multiple CPU threads whenever possible. You can disable the parallelism of PyTorch by calling `torch.set_num_threads(1)`, at the cost of slower CPU operations.

Thank you! It is useful😊
