### ISSUE TITLE
Torchdrug on Apple Silicon?

### ISSUE THREAD

**Issue by SANAZKAZEMINIA** [DeepGraphLearning/torchdrug#210]
Hi everyone, 

I have apple silicon chip. 

i am having trouble getting started with torchdrug. 

"from torchdrug import core, models, tasks

model = models.GIN(input_dim=dataset.node_feature_dim,
                   hidden_dims=[256, 256, 256, 256],
                   short_cut=True, batch_norm=True, concat_hidden=True)"
i get the following error message :

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 3
      1 from torchdrug import core, models, tasks
----> 3 model = models.GIN(input_dim=dataset.node_feature_dim,
      4                    hidden_dims=[256, 256, 256, 256],
      5                    short_cut=True, batch_norm=True, concat_hidden=True)

File ~/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    230 if not kwsyntax:
    231     args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)

File ~/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/torchdrug/core/core.py:288, in _Configurable.__new__.<locals>.wrapper(init, self, *args, **kwargs)
    286     config.pop(k)
    287 self._config = dict(config)
--> 288 return init(self, *args, **kwargs)

File ~/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/torchdrug/models/gin.py:48, in GraphIsomorphismNetwork.__init__(self, input_dim, hidden_dims, edge_input_dim, num_mlp_layer, eps, learn_eps, short_cut, batch_norm, activation, concat_hidden, readout)
     46 for i in range(len(self.dims) - 1):
     47     layer_hidden_dims = [self.dims[i + 1]] * (num_mlp_layer - 1)
---> 48     self.layers.append(layers.GraphIsomorphismConv(self.dims[i], self.dims[i + 1], edge_input_dim,
     49                                                    layer_hidden_dims, eps, learn_eps, batch_norm, activation))
     51 if readout == "sum":
     52     self.readout = layers.SumReadout()

File ~/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/torchdrug/layers/conv.py:305, in GraphIsomorphismConv.__init__(self, input_dim, output_dim, edge_input_dim, hidden_dims, eps, learn_eps, batch_norm, activation)
    303     self.eps = nn.Parameter(eps)
    304 else:
--> 305     self.register_buffer("eps", eps)
    306 if batch_norm:
    307     self.batch_norm = nn.BatchNorm1d(output_dim)

File ~/anaconda3/envs/pythonProject1/lib/python3.9/site-packages/torchdrug/patch.py:71, in PatchedModule.register_buffer(self, name, tensor, persistent)
     68 if '_buffers' not in self.__dict__:
     69     raise AttributeError(
     70         "cannot assign buffer before Module.__init__() call")
---> 71 elif not isinstance(name, torch._six.string_classes):
     72     raise TypeError("buffer name should be a string. "
     73                     "Got {}".format(torch.typename(name)))
     74 elif '.' in name:

AttributeError: module 'torch' has no attribute '_six'

Does anyone have any work around?

Thanks.

**Comment by Ac2zoom** [comment]
Looks like this might be related to this item regarding `torch._six` being removed in PyTorch 2.0.1 if you're using that instead of 1.8: https://github.com/DeepGraphLearning/torchdrug/issues/204

**Comment by SANAZKAZEMINIA** [comment]
Hey, thanks for your response. I managed to make it work by doing installation in a conda env using the source code - it's now running.
