### ISSUE TITLE
G2Gs retrosynthesis performance can not be reproduced?

### ISSUE THREAD

**Issue by chaoyan1037** [DeepGraphLearning/torchdrug#22]
Hello,

Thanks for sharing this library! The reproduced retrosynthesis results of [G2Gs](https://arxiv.org/pdf/2003.12725.pdf) are different from the paper. Does this mean that the results of the G2Gs paper are not reproducible? 

These are the reported results from the [Torchdrug tutorial](https://torchdrug.ai/docs/tutorials/retrosynthesis.html#id3):
```
top-1 accuracy: 0.47541
top-3 accuracy: 0.741803
top-5 accuracy: 0.827869
top-10 accuracy: 0.879098
```

**Comment by KiddoZhu** [comment]
Hi! G2Gs is reproducible. Please refer to the results here https://torchdrug.ai/docs/benchmark/retrosynthesis.html

In the tutorial, we reduce the computation cost for fast demonstration. If you want to reproduce the result, you need to use at least 100 and 50 epochs for training center identification and synthon completion respectively. You also need to spend much more budget for beam search, like `center_topk=3, num_synthon_beam=10, max_prediction=20`.

**Comment by chaoyan1037** [comment]
Thanks for the help! Will try it!

**Comment by DimGorr** [comment]
Hi! @chaoyan1037 have you eventually tried to reproduce it? And if yes have you obtained the desired results?
