### ISSUE TITLE
How to use the generation model to optimize specific molecules

### ISSUE THREAD

**Issue by Yongrui-Wang** [DeepGraphLearning/torchdrug#23]
Hi！
How to use the generation model to optimize specific molecules? For example, I have trained a generation model of QED and logP "GCPN"_ zinc250k_ 1epoch_ finetune. pkl ",and  I have one or some smiles of known molecules. I want to generate some molecules with better QED and logP properties based on my own molecules through this generation model. How can I achieve it?

What's more, how is it implemented on the official website Tutorials: Molecule Generation? I don't have such output during and after the training

The results are as follows:
```

(5.63, 'CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=C(I)C(C)(C)C')
(5.60, 'CCC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC(C)(C)CCC')
(5.44, 'CC=CC=CC=CC(Cl)=CC=CC=CC=CC=CC=C(C)C=CC=CC=C(C)C=CC(Br)=CC=CCCC')
(5.35, 'CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=CC=C(CC)C(C)C')
...
```
Thank you very much!

**Comment by shichence** [comment]
For the first question, you could hack the code in [task/generation.py/reinforce_forward](https://github.com/DeepGraphLearning/torchdrug/blob/6dc22b4a8cebbda402334f9748ce0e6198e0014d/torchdrug/tasks/generation.py#L143), and replace the graph generated from scratch by your own molecules.

For the second question, please check out the [colab](https://colab.research.google.com/drive/1JEMiMvSBuqCuzzREYpviNZZRVOYsgivA#scrollTo=f0j0CLW5yJTL).

**Comment by Yongrui-Wang** [comment]
THANKS

**Comment by goga0001** [comment]
> shichence
Hello,

I have similar question but I was wondering how can I use the generation model to generate specific molecules? I have a small dataset of molecules I am interested in generating, should I use ZINC250k dataset to train GraphAF model on and then use property optimization to generate novel molecules with desired QED, logP properties or should I use my small dataset(around 4k) to train the GraphAF model?

Thank you kindly,

Looking forward for your reply
