### ISSUE TITLE
Passing CIF file directly into TorchDrug Protein?

### ISSUE THREAD

**Issue by gtamer2** [DeepGraphLearning/torchdrug#231]
Hi folks,

Does Torchdrug support any compatibility with CIF files, or are there any sponsored solutions for converting CIF files into torchdrug.data.Protein ready PDB files?

I have browsed through past issues and haven't seen CIF files mentioned previously. I know it is possible to convert CIF files to PDB files [with a tool like BioPython](https://chat.openai.com/share/a7c8d13a-cc15-4600-b18b-d8f925156e97), but this can be buggy.

My use case is that I have a dataset of CIF files I'd like to feed into Torchdrug's GearNet GNN model.

Thanks in advance!

**Comment by fourier20laplace** [comment]
Are there any possible solutions for this issue? Any help would be greatly appreciated! 😊
