### ISSUE TITLE
Saving model in Get Started guide: TypeError: Object of type Subset is not JSON serializable

### ISSUE THREAD

**Issue by schinto** [DeepGraphLearning/torchdrug#26]
Following the [Get Started](https://torchdrug.ai/get_started)  guide, the following error is thrown
```
import json

with open("clintox_gin.json", "w") as fout:
    json.dump(solver.config_dict(), fout)
solver.save("clintox_gin.pth")
```

**TypeError: Object of type Subset is not JSON serializable**

**Comment by Oxer11** [comment]
Thanks for pointing out this bug! This has been fixed in commit d570083.
