### ISSUE TITLE
ChEMBLFiltered fails with FileNotFoundError 

### ISSUE THREAD

**Issue by schinto** [DeepGraphLearning/torchdrug#36]
```python
import torch
from torchdrug import data, datasets
dataset = datasets.ChEMBLFiltered("~/molecule-datasets/")
```
fails with
```
~/opt/anaconda3/envs/drugs/lib/python3.8/site-packages/torchdrug/datasets/chembl_filtered.py in _load_chembl_with_labels_dataset(root_path)
    103 def _load_chembl_with_labels_dataset(root_path):
    104     # 1. load folds and labels
--> 105     f=open(os.path.join(root_path, 'folds0.pckl'), 'rb')
    106     folds=pickle.load(f)
    107     f.close()

FileNotFoundError: [Errno 2] No such file or directory: './temp/chem_dataset/dataset/chembl_filtered/raw/folds0.pckl'
```

However, file `folds0.pckl` is written to
`~/molecule-datasets/chem_dataset/dataset/chembl_filtered/raw/folds0.pckl`

`ChEMBLFiltered` seems to download all MoleculeNet related datasets.
Is that intended behaviour?

**Comment by Oxer11** [comment]
Fixed in b779eef.
Now we use a different way to downloading the chembel fltered dataset. Instead of downloading the full chembl dataset and then preprocessing it, now we download the preprocessed chembl filtered file.
