### ISSUE TITLE
undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by kellpossible** [DeepGraphLearning/torchdrug#38]
I installed torchdrug with 

```bash
conda install -c milagraph -c conda-forge torchdrug
```

I've performed the verification for pytorch https://pytorch.org/get-started/locally/#linux-verification

This is the error I get when I try `import torchdrug`:

```txt
OSError:  <redacted>/.venv/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

Operating system: ArchLinux

**Comment by KiddoZhu** [comment]
Hi! I think this is an issue caused by inconsistent versions between PyTorch and torch-scatter. Could you check your PyTorch version, and follow the instructions in https://github.com/rusty1s/pytorch_scatter to install the corresponding version for torch-scatter?

TorchDrug should be robust to any PyTorch / torch-scatter versions after 1.4.0.

**Comment by kellpossible** [comment]
Thanks yes I see now this is probably a problem more with torch_scatter!

> You can now install pytorch-scatter via Anaconda for all major OS/PyTorch/CUDA combinations hugs Given that you have pytorch >= 1.8.0 installed, simply run

https://github.com/rusty1s/pytorch_scatter

```bash
$ conda list
...
pytorch                   1.9.0           cuda112py38h3d13190_1    conda-forge
pytorch-gpu               1.9.0           cuda112py38h0bbbad9_1    conda-forge
pytorch_scatter           2.0.7            py38he8ac336_0    conda-forge
...
torchdrug                 0.1.1                  hf14caf7    milagraph
,,,
```

I'll try installing the version from their `pyg` channel (instead of `conda-forge`) that they suggest.

**Comment by KiddoZhu** [comment]
Although I don't know the reason, it seems that torch-scatter installed from conda doesn't check its consistency with PyTorch in most cases. Manually installing torch-scatter from pip with explicit PyTorch version works more smoothly. Maybe you can also try pip.

**Comment by kellpossible** [comment]
Thanks yes I'll try in the future, I was just testing out dependency management using for a future project. Conclusion is that both conda and pip ecosystems have their own challenges! We can probably close this issue for now.
