### ISSUE TITLE
Customized target for retrosynthesis

### ISSUE THREAD

**Issue by julia78118** [DeepGraphLearning/torchdrug#48]
Hi, thanks for sharing this repo!

I am wondering how I could input arbitrary target/product for retrosynthesis analysis? What target format would the model required besides SMILES? In the notebook, it's performing prediction on USPTO dataset. I am interested in knowing how I could apply this model to the target outside of USPTO.

Thanks!!

**Comment by julia78118** [comment]
@KiddoZhu  Thanks for getting back to me!
I was getting some error when inference with product/target only; now I know it's the reaction type missing. :)
I would like to clarify a bit with you regarding use a center identification task without the reaction feature. Are you referring to something like this:

```
reactant, product = reaction_dataset[i]["graph"]

product_only_dataset[i]["graph"] = product
```

and then do the center identification task training?

and for the synthon task, do both reactant and synthon stay in the training data?

Thank you in advance!

**Comment by KiddoZhu** [comment]
You don't have to tweak the dataset. If you don't use reaction feature in center identification & synthon completion, then they will automatically ignore `batch["reaction"]` in training and inference. The two in the tutorial already satisfy this situation.

For the synthon task, the dataset should be loaded with argument `as_synthon=True`, then each sample `batch["graph"]` is a pair of reactant and synthon. See [the visualization in our tutorial](https://torchdrug.ai/docs/tutorials/retrosynthesis.html#prepare-the-dataset) for more details.

**Comment by julia78118** [comment]
Thanks for getting back to me. This is really helpful!
