### ISSUE TITLE
What all molecule generation models can be used?

### ISSUE THREAD

**Issue by ritwizsinha** [DeepGraphLearning/torchdrug#56]
I wanted to ask are GCPN and GRAPHAF the only two graph generative models used, can I integrate other models like ZINC, ORGAN and JT VAE for molecular generation?

**Comment by shichence** [comment]
Yes, you can implement customized graph generation models based on `TouchDrug`. The simplest way is to just inherit modules provided in `TouchDrug`.
I'm not aware of the ORGAN, but we are implementing a generalized version of JT-VAE currently. Stay tuned for the new model.
