### ISSUE TITLE
PackageNotFoundError: Packages missing in current channels:  torchdrug

### ISSUE THREAD

**Issue by DreamMemory001** [DeepGraphLearning/torchdrug#6]
i use `conda install -c milagraph -c conda-forge torchdrug` to install torchdrug, but it show this.  Can u  tell  what cause this problem? Thanks u.  in my environment : torch==1.8 ,py ==3.6

**Comment by KiddoZhu** [comment]
Hi! I found this is an issue due to the python version in our conda recipe. We will soon fix this in conda.

Btw, TorchDrug requires the metaclass feature and thus is incompatible with python < 3.7. Maybe you can try install it from source on a python 3.7 or 3.8?

**Comment by DreamMemory001** [comment]
Thanks for your reply. Ok, I will try it at once. And it is great for you to change in readme.md and website on problem of python version at once.  Thumbs up for your efficiency
