### ISSUE TITLE
only 3 types of bond?

### ISSUE THREAD

**Issue by levlai** [DeepGraphLearning/torchdrug#79]
Hi, I would realy appretiate you support!
This is what we get for bond_types:    
def bond_types(self):
```
               ....
                bond_types.update(graph.edge_list[:, 2].tolist())
```

Edge_list is only single, double, triple, according to this peace of code in molecule.py:
```
...
            type = str(bond.GetBondType())
            stereo = bond.GetStereo()
            if stereo:
                _atoms = [a for a in bond.GetStereoAtoms()]
            else:
                _atoms = [0, 0]
            if type not in cls.bond2id:
                continue
            type = cls.bond2id[type]
            h, t = bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
            edge_list += [[h, t, type], [t, h, type]]
            # always explicitly store aromatic bonds, no matter kekulize or not
            if bond.GetIsAromatic():
                type = cls.bond2id["AROMATIC"]
...

```
As a consequence I only get 3 bond_types, although  there is 4 (aromatic is missing).
Is there anything I am doing/assuming wrong here, or it is a bug?

**Comment by KiddoZhu** [comment]
Hi! The edge list contains 3 bond types if `kekulize=True` and 4 bond types otherwise. The variable `graph.bond_type` always contains 4 bond types. If you want explicit bond types as features, you may use `graph.bond_type` instead of `graph.edge_list[:, 2]`.
