### ISSUE TITLE
Runtime Error in graph.py

### ISSUE THREAD

**Issue by jannisborn** [DeepGraphLearning/torchdrug#83]
During property optimization, if all molecules are invalid, the following line fails:
https://github.com/DeepGraphLearning/torchdrug/blob/119002a43b67d142b2206f809724dbf25677b95b/torchdrug/data/graph.py#L1222

with the error:
```sh
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

I thought I can fix this by increasing the batch size so that always at least one molecule is valid in the batch but due to the resampling this does not work either:
```sh
19:18:53   2 / 16 molecules are invalid even after 20 resampling
19:18:53   2 / 14 molecules are invalid even after 20 resampling
19:18:53   2 / 12 molecules are invalid even after 20 resampling
19:18:54   5 / 10 molecules are invalid even after 20 resampling
19:18:54   1 / 5 molecules are invalid even after 20 resampling
19:18:54   2 / 4 molecules are invalid even after 20 resampling
19:18:54   1 / 1 molecules are invalid even after 20 resampling
```

Then, I would like to increase the `max_resample` parameter but it's hardcoded, so there is no way to control it.

versions:
- torch: 1.11.0
- torchdrug: 0.1.2

**Fix**:
The following should be more robust but do the same job:
```py
if len(count) > 0 and max(count) > 1:
```

**Comment by KiddoZhu** [comment]
Good point! We will fix it.
