### ISSUE TITLE
The Subset class imported from torch.utils.data isn't Configurable

### ISSUE THREAD

**Issue by Oxer11** [DeepGraphLearning/torchdrug#85]
In `patch.py`, we manually modify all datasets in the `torch.utils.data.dataset` to make it configurable. However, the line below only sets the attributes of `torch.utils.data.dataset` not `torch.utils.data`, which leaves all `Dataset` imported from the latter unchanged. There is a similar problem for `torch.optim.lr_scheduler`.

https://github.com/DeepGraphLearning/torchdrug/blob/119002a43b67d142b2206f809724dbf25677b95b/torchdrug/patch.py#L156

**Comment by KiddoZhu** [comment]
Fixed in f29dc55
