### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by utkusaglm** [DeepGraphLearning/torchdrug#88]
TorchDrug library can not be installed on the apple silicon platform.

**Comment by GZ82** [comment]
the installation methods in docs: https://torchdrug.ai/docs/installation.html
works for me
but I have problem to run the training using cpu, I guess gpu not work for Macbook because device is mps?

**Comment by saglamutku** [comment]
It works now.

**Comment by GZ82** [comment]
> It works now.

 updates in recent days? if yes I will try to reinstall it. I have problem to run solver using cpu, the problem seems related to ninja and torch_ext.so, have raised the issue here: #229

**Comment by saglamutku** [comment]
> > It works now.
> 
> updates in recent days? if yes I will try to reinstall it. I have problem to run solver using cpu, the problem seems related to ninja and torch_ext.so, have raised the issue here: #229

the comment was about the installation not training but I also tried training process and as you can see It works. Could you try it with new env?
<img width="441" alt="Screenshot 2023-11-08 at 18 54 31" src="https://github.com/DeepGraphLearning/torchdrug/assets/58150504/6cd6251c-8d66-455a-9668-132156e0b74d">
